//! The recovery code (plan-drive §8.2, decision 2026-09-27: generated by the app, never chosen).
//! Thirty characters of Crockford's base32 —150 bits from the phone's randomness— shown once and
//! written down. With that much entropy there is nothing to stretch: the key that wraps the vault
//! key is derived from the code directly, and whoever holds `key.ftv` without the code has a
//! 2^150 search ahead, whatever machine they own.

use anyhow::{ensure, Result};

const ALPHABET: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";
/// How many characters a code has, and how they are grouped when shown.
pub const LENGTH: usize = 30;
const GROUP: usize = 5;

/// A fresh code, grouped for reading: `XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`.
pub fn new_code() -> String {
    let bytes: [u8; LENGTH] = rand::random();
    let raw: String = bytes.iter().map(|byte| ALPHABET[(byte % 32) as usize] as char).collect();
    raw.as_bytes().chunks(GROUP).map(|group| std::str::from_utf8(group).expect("ascii")).collect::<Vec<_>>().join("-")
}

/// A code as the user typed it, made canonical: upper case, no separators, and the letters
/// people confuse (`O`, `I`, `L`) read as the digits they look like. Fails if it is not a code.
pub fn normalize(typed: &str) -> Result<String> {
    let mut clean = String::with_capacity(LENGTH);
    for symbol in typed.chars() {
        if symbol == '-' || symbol.is_whitespace() {
            continue;
        }
        let upper = match symbol.to_ascii_uppercase() {
            'O' => '0',
            'I' | 'L' => '1',
            other => other,
        };
        ensure!(ALPHABET.contains(&(upper as u8)), "that is not a recovery code");
        clean.push(upper);
    }
    ensure!(clean.len() == LENGTH, "a recovery code has {LENGTH} characters");
    Ok(clean)
}

/// The key that wraps the vault key in the cloud, from the code alone.
pub fn wrap_key(code: &str) -> Result<[u8; 32]> {
    let clean = normalize(code)?;
    Ok(blake3::derive_key("FlickerTalk vault v1 recovery code", clean.as_bytes()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_code_is_thirty_symbols_from_the_alphabet_grouped_for_reading() {
        let code = new_code();
        assert_eq!(code.len(), LENGTH + LENGTH / GROUP - 1);
        assert_eq!(normalize(&code).unwrap().len(), LENGTH);
        assert!(normalize(&code).unwrap().bytes().all(|byte| ALPHABET.contains(&byte)));
        assert_ne!(new_code(), code);
    }

    #[test]
    fn typing_is_forgiven_but_not_a_wrong_code() {
        let code = "abcde-fghjk-mnpqr-stvwx-yz012-34567";
        let same = normalize(code).unwrap();
        assert_eq!(normalize("ABCDE FGHJK MNPQR STVWX YZ012 34567").unwrap(), same);
        assert_eq!(normalize("ABCDEFGHJKMNPQRSTVWXYZO1234567").unwrap(), normalize("ABCDEFGHJKMNPQRSTVWXYZ01234567").unwrap());
        assert!(normalize("l").is_err(), "too short");
        assert!(normalize("ABCDE-FGHJK-MNPQR-STVWX-YZ012-3456U").is_err(), "U is not in the alphabet");
        assert!(normalize("").is_err());
        assert_eq!(wrap_key(code).unwrap(), wrap_key("ABCDE FGHJK MNPQR STVWX YZ012 34567").unwrap());
        assert_ne!(wrap_key(code).unwrap(), wrap_key("ABCDE-FGHJK-MNPQR-STVWX-YZ012-34568").unwrap());
    }
}
