[workspace]
resolver = "2"
# Crates are added here as they appear (Plan §82).
members = ["src-tauri", "crates/ft-webrtc", "crates/ft-poc"]

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
